# Generated by Django 4.2.10 on 2024-06-08 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="flight",
            name="flight_name",
            field=models.CharField(max_length=200),
        ),
    ]
